# Generated by Django 5.2.6 on 2025-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
