# Generated by Django 5.2.6 on 2025-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_station_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journey",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="journeys", to="station.crew"
            ),
        ),
    ]
